# Generated by Django 4.0.7 on 2023-04-16 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0084_characteraudit_last_update_loyaltypoints_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpMemberTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoff_date', models.DateTimeField()),
                ('logon_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='member_tracking', to='corptools.characteraudit')),
            ],
        ),
    ]
